version: '3.8'
services:
  app:
    image: php:8.2-fpm
    container_name: pet-laravel
    working_dir: /var/www
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    depends_on:
      - db
    command: >
      sh -c "docker-php-ext-install pdo pdo_mysql && php-fpm"

  db:
    image: mysql:latest
    container_name: pet-mysql
    restart: always
    environment:
      MYSQL_DATABASE: pet_appointments
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
